# Generated by Django 4.2.1 on 2023-06-08 13:27

from django.db import migrations, models


def init_term_settings(apps, schema_editor):
    TermSettings = apps.get_model("term", "TermSettings")
    settings = [
        TermSettings(settings_type=1, description="Minimum amount", value=1000),
        TermSettings(settings_type=2, description="Amount block", value=10),
        TermSettings(settings_type=3, description="Early renewal days", value=30),
    ]
    TermSettings.objects.bulk_create(settings)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TermSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settings_type",
                    models.IntegerField(
                        choices=[
                            (1, "minimum amount"),
                            (2, "amount multiple"),
                            (3, "early renewal days"),
                        ]
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("value", models.FloatField()),
            ],
            options={
                "db_table": "term_settings",
            },
        ),
        migrations.RunPython(init_term_settings),
    ]
