# Generated by Django 4.2.1 on 2023-06-08 14:18

from django.db import migrations, models


def init_term(apps, schema_editor):
    Term = apps.get_model("term", "Term")
    terms = [
        Term(title="Wealth builder", days=90),
        Term(title="Wealth builder", days=180),
        Term(title="Wealth builder", days=270),
        Term(title="Wealth builder", days=360),
    ]
    Term.objects.bulk_create(terms)


class Migration(migrations.Migration):
    dependencies = [
        ("term", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("days", models.IntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "term",
            },
        ),
        migrations.RunPython(init_term),
    ]
