# Generated by Django 4.2.2 on 2023-06-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("term", "0002_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="is_enable",
            field=models.BooleanField(default=True),
        ),
    ]
