# Generated by Django 5.0.6 on 2024-06-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0003_term_is_enable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="term",
            options={"ordering": ["id"]},
        ),
    ]
