# Generated by Django 5.0.6 on 2024-06-29 07:35

from django.db import migrations, models


def update_term_settings(apps, schema_editor):
    TermSettings = apps.get_model("term", "TermSettings")
    settings = [
        TermSettings(settings_type=4, description="Shares allowance rate", value=1),
    ]
    TermSettings.objects.bulk_create(settings)


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0004_alter_term_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termsettings",
            name="settings_type",
            field=models.IntegerField(
                choices=[
                    (1, "minimum amount"),
                    (2, "amount multiple"),
                    (3, "early renewal days"),
                    (4, "shares allowance rate"),
                ]
            ),
        ),
        migrations.RunPython(update_term_settings),
    ]
