# Generated by Django 4.2.1 on 2023-05-21 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.IntegerField(
                        choices=[
                            (1, "usdt"),
                            (2, "sponsor"),
                            (3, "shares"),
                            (4, "trade"),
                            (5, "tiering"),
                        ]
                    ),
                ),
                ("open_balance", models.FloatField(default=0)),
                ("available_balance", models.FloatField(default=0)),
                ("is_transferable", models.BooleanField(default=True)),
                ("is_withdrawable", models.BooleanField(default=True)),
                ("is_enable", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "account",
                "unique_together": {("account_type", "user_id")},
            },
        ),
    ]
