# Generated by Django 4.2.1 on 2023-06-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="code",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
