# Generated by Django 4.2.1 on 2023-06-12 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0002_contract_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="process_end",
            new_name="contract_end",
        ),
    ]
