# Generated by Django 4.2.1 on 2023-06-12 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0003_rename_process_end_contract_contract_end"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="term_rate_limit",
            new_name="limit_rate",
        ),
    ]
