# Generated by Django 4.2.2 on 2023-07-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract", "0004_rename_term_rate_limit_contract_limit_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_status",
            field=models.IntegerField(
                choices=[
                    (1, "inactive"),
                    (2, "open"),
                    (3, "closed"),
                    (4, "completed"),
                    (5, "suspended"),
                ],
                default=1,
            ),
        ),
    ]
