# Generated by Django 5.0.6 on 2024-06-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0006_alter_contract_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="roi_rate",
            new_name="roi_rate_from",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contract_end",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contract_value",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="invested_value",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="investment_end",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="investment_start",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="limit_rate",
        ),
        migrations.AddField(
            model_name="contract",
            name="roi_rate_to",
            field=models.FloatField(default=0),
        ),
    ]
