# Generated by Django 5.0.6 on 2024-06-29 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0007_rename_roi_rate_contract_roi_rate_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="bonus_income_cap_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="contract",
            name="share_allowance_rate",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="ContractRoiLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roi_rate", models.FloatField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roi_logs",
                        to="contract.contract",
                    ),
                ),
            ],
            options={
                "db_table": "contract_roi_log",
                "ordering": ["id"],
            },
        ),
    ]
