# Generated by Django 5.0.6 on 2024-06-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0008_contract_bonus_income_cap_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="amount_multiple",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="contract",
            name="minimum_amount",
            field=models.FloatField(default=0),
        ),
    ]
