# Generated by Django 5.0.6 on 2024-06-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0009_contract_amount_multiple_contract_minimum_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="roi_daily_rate",
            field=models.FloatField(default=0),
        ),
    ]
