# Generated by Django 4.2.1 on 2023-06-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stake", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stake",
            name="available_amount",
            field=models.FloatField(default=0),
        ),
    ]
