# Generated by Django 5.0.6 on 2024-06-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stake", "0002_stake_available_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stake",
            options={"ordering": ["id"]},
        ),
    ]
