# Generated by Django 4.2.2 on 2023-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invest", "0002_investbonustransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investbonustransaction",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "pending"),
                    (2, "authorized"),
                    (3, "voided"),
                    (4, "processing"),
                ],
                default=4,
            ),
        ),
    ]
