# Generated by Django 4.2.3 on 2023-08-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invest", "0003_alter_investbonustransaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invest",
            name="invest_status",
            field=models.IntegerField(
                choices=[(1, "active"), (2, "suspended"), (3, "completed")], default=1
            ),
        ),
    ]
