# Generated by Django 5.0.6 on 2024-06-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0006_remove_invest_invest_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invest",
            name="bonus_total_payout",
            field=models.FloatField(default=0),
        ),
    ]
