# Generated by Django 4.2.1 on 2023-05-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                (
                    "bank_country",
                    models.CharField(
                        help_text="Using ISO 3 country code", max_length=3
                    ),
                ),
                ("bank_region", models.CharField(max_length=255)),
                ("bank_branch", models.CharField(max_length=255)),
                (
                    "bank_status",
                    models.IntegerField(
                        choices=[
                            (1, "pending"),
                            (2, "authorized"),
                            (3, "deactivated"),
                            (4, "rejected"),
                        ],
                        default=1,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "account_bank",
            },
        ),
    ]
