# Generated by Django 5.0.6 on 2024-06-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_alter_bank_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bank",
            options={"ordering": ["id"]},
        ),
    ]
