# Generated by Django 4.2.1 on 2023-05-31 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("upload", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
                (
                    "wallet_type",
                    models.IntegerField(
                        choices=[(1, "deposit"), (2, "withdrawal")], default=2
                    ),
                ),
                (
                    "wallet_status",
                    models.IntegerField(
                        choices=[
                            (1, "pending"),
                            (2, "authorized"),
                            (3, "deactivated"),
                            (4, "rejected"),
                        ],
                        default=1,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_wallet",
                        to="upload.upload",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "blockchain_wallet",
            },
        ),
    ]
