# Generated by Django 4.2.1 on 2023-06-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referral", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralNetwork",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("referrer_username", models.CharField(max_length=150)),
                ("lvl", models.IntegerField()),
                ("network", models.CharField(max_length=255)),
                (
                    "network_type",
                    models.IntegerField(choices=[(1, "downline"), (2, "upline")]),
                ),
            ],
            options={
                "db_table": "referral_network",
                "managed": False,
            },
        ),
    ]
