# Generated by Django 4.2.2 on 2023-07-15 13:22

from django.db import migrations, models
import django.db.models.deletion


def init_referral_bonus_settings(apps, schema_editor):
    ReferralBonusSettings = apps.get_model("referral", "ReferralBonusSettings")
    settings = [
        ReferralBonusSettings(rate=0.02, term_id=1),
        ReferralBonusSettings(rate=0.06, term_id=2),
        ReferralBonusSettings(rate=0.1, term_id=3),
        ReferralBonusSettings(rate=0.15, term_id=4),
    ]
    ReferralBonusSettings.objects.bulk_create(settings)


class Migration(migrations.Migration):
    dependencies = [
        ("term", "0003_term_is_enable"),
        ("referral", "0002_referralnetwork"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralBonusSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.FloatField()),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "term",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_bonus_settings",
                        to="term.term",
                    ),
                ),
            ],
            options={
                "db_table": "referral_bonus_settings",
            },
        ),
        migrations.RunPython(init_referral_bonus_settings),
    ]
