# Generated by Django 4.2.2 on 2023-07-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referral", "0003_referralbonussettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralBonusTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referrer_id", models.IntegerField()),
                ("term_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("amount", models.FloatField()),
                ("rate", models.FloatField()),
                ("bonus", models.FloatField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "pending"), (2, "authorized"), (3, "voided")],
                        default=1,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "referral_bonus_transaction",
            },
        ),
    ]
