# Generated by Django 4.2.2 on 2023-07-20 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("term", "0003_term_is_enable"),
        ("referral", "0004_referralbonustransaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralbonustransaction",
            name="referrer_id",
        ),
        migrations.RemoveField(
            model_name="referralbonustransaction",
            name="term_id",
        ),
        migrations.RemoveField(
            model_name="referralbonustransaction",
            name="user_id",
        ),
        migrations.AddField(
            model_name="referralbonustransaction",
            name="referrer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_bonus_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralbonustransaction",
            name="term",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_bonus_transactions",
                to="term.term",
            ),
        ),
        migrations.AddField(
            model_name="referralbonustransaction",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsor_bonus_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
