# Generated by Django 4.2.2 on 2023-07-27 14:02
import os

from django.db import migrations, models


def load_sp_referral_network_stored_procedure(apps, schema_editor):
    # Load the SQL file
    sql_file = os.path.join(os.path.dirname(__file__), "sql/sp_referral_network.sql")
    with open(sql_file, "r") as f:
        sql = f.read()

    # Run the SQL to create the stored procedure
    schema_editor.connection.in_atomic_block = False
    schema_editor.execute(sql)


def load_sp_referral_roi_network_stored_procedure(apps, schema_editor):
    # Load the SQL file
    sql_file = os.path.join(
        os.path.dirname(__file__), "sql/sp_referral_roi_network.sql"
    )
    with open(sql_file, "r") as f:
        sql = f.read()

    # Run the SQL to create the stored procedure
    schema_editor.connection.in_atomic_block = False
    schema_editor.execute(sql)


class Migration(migrations.Migration):
    dependencies = [
        ("referral", "0005_remove_referralbonustransaction_referrer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralRoiNetwork",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("referrer_username", models.CharField(max_length=150)),
                ("lvl", models.IntegerField()),
                ("network", models.CharField(max_length=255)),
                (
                    "network_type",
                    models.IntegerField(choices=[(1, "downline"), (2, "upline")]),
                ),
                ("invest_bonus", models.FloatField()),
            ],
            options={
                "db_table": "referral_roi_network",
                "managed": False,
            },
        ),
        migrations.RunPython(load_sp_referral_network_stored_procedure),
        migrations.RunPython(load_sp_referral_roi_network_stored_procedure),
    ]
