# Generated by Django 5.0.6 on 2024-06-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0006_referralroinetwork"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referral",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="referralbonussettings",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="referralbonustransaction",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="referralnetwork",
            options={"managed": False, "ordering": ["-referrer_id", "user_id"]},
        ),
        migrations.AlterModelOptions(
            name="referralroinetwork",
            options={"managed": False, "ordering": ["-referrer_id", "user_id"]},
        ),
    ]
