# Generated by Django 4.2.1 on 2023-05-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.IntegerField(
                        choices=[
                            (1, "admin_transaction"),
                            (2, "transfer_transaction"),
                            (3, "transfer_fee"),
                            (4, "withdrawal_transaction"),
                            (5, "withdrawal_fee"),
                            (6, "deposit_transaction"),
                            (7, "shares_transaction"),
                            (8, "sponsor_bonus"),
                            (9, "trading_bonus"),
                            (10, "tiering_bonus"),
                        ]
                    ),
                ),
                (
                    "transaction_status",
                    models.IntegerField(
                        choices=[(1, "authorized"), (2, "voided")], default=1
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
            },
        ),
    ]
