# Generated by Django 4.2.1 on 2023-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_status",
            field=models.IntegerField(
                choices=[(1, "authorized"), (2, "voided"), (3, "pending")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.IntegerField(
                choices=[
                    (1, "admin_transaction"),
                    (2, "transfer_transaction"),
                    (3, "transfer_fee"),
                    (4, "withdrawal_transaction"),
                    (5, "withdrawal_fee"),
                    (6, "deposit_transaction"),
                    (7, "shares_transaction"),
                    (8, "sponsor_bonus"),
                    (9, "trading_bonus"),
                    (10, "tiering_bonus"),
                    (11, "stake_purchase_transaction"),
                ]
            ),
        ),
    ]
