# Generated by Django 4.2.1 on 2023-05-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_data", models.FileField(null=True, upload_to="media/%Y/%m/%d/")),
                ("date_uploaded", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "upload",
            },
        ),
    ]
