# Generated by Django 4.2.2 on 2023-07-27 07:04

from django.db import migrations, models
import django.db.models.deletion


def init_bonus_settings(apps, schema_editor):
    GoldmineBonusSettings = apps.get_model("goldmine", "GoldmineBonusSettings")
    settings = [
        GoldmineBonusSettings(rate=0.01, level=5, term_id=2),
        GoldmineBonusSettings(rate=0.02, level=10, term_id=3),
        GoldmineBonusSettings(rate=0.03, level=15, term_id=4),
    ]
    GoldmineBonusSettings.objects.bulk_create(settings)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("term", "0003_term_is_enable"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldmineBonusSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.FloatField()),
                ("level", models.IntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goldmine_bonus_settings",
                        to="term.term",
                    ),
                ),
            ],
            options={
                "db_table": "goldmine_bonus_settings",
            },
        ),
        migrations.RunPython(init_bonus_settings),
    ]
