# Generated by Django 4.2.2 on 2023-07-28 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goldmine", "0002_rename_level_goldminebonussettings_max_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldmineBonusTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_invest_bonus", models.FloatField()),
                ("level", models.IntegerField()),
                ("bonus", models.FloatField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "pending"), (2, "authorized"), (3, "voided")],
                        default=1,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goldmine_bonus_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "goldmine_bonus_transaction",
            },
        ),
    ]
