# Generated by Django 5.0.6 on 2024-06-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goldmine", "0003_goldminebonustransaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goldminebonussettings",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="goldminebonustransaction",
            options={"ordering": ["id"]},
        ),
    ]
