# Generated by Django 5.0.6 on 2024-06-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="userattachments",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="usercontact",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="userdetails",
            options={"ordering": ["id"]},
        ),
    ]
