# Generated by Django 4.2.1 on 2023-06-03 14:55

from django.db import migrations, models


def init_withdrawal_settings(apps, schema_editor):
    WithdrawalSettings = apps.get_model("withdrawal", "WithdrawalSettings")
    settings = [
        WithdrawalSettings(
            settings_type=1,
            description="Withdrawal block",
            rate=10,
        ),
        WithdrawalSettings(
            settings_type=2,
            description="Bank service fee (%)",
            rate=0.1,
        ),
        WithdrawalSettings(
            settings_type=3,
            description="Bank minimum withdrawal",
            rate=100,
        ),
        WithdrawalSettings(
            settings_type=4,
            description="Blockchain service fee (%)",
            rate=0.1,
        ),
        WithdrawalSettings(
            settings_type=5,
            description="Blockchain minimum withdrawal",
            rate=100,
        ),
        WithdrawalSettings(
            settings_type=6,
            description="Blockchain gas fee",
            rate=10,
        ),
    ]
    WithdrawalSettings.objects.bulk_create(settings)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WithdrawalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settings_type",
                    models.IntegerField(
                        choices=[
                            (1, "withdraw multiple"),
                            (2, "bank minimum withdraw"),
                            (3, "bank service fee"),
                            (4, "blockchain minimum withdraw"),
                            (5, "blockchain service fee"),
                            (6, "blockchain gas fee"),
                        ]
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("rate", models.FloatField()),
            ],
            options={
                "db_table": "withdrawal_settings",
            },
        ),
        migrations.RunPython(init_withdrawal_settings),
    ]
