# Generated by Django 4.2.1 on 2023-06-04 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
        ("withdrawal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalBlockchain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
                ("transaction_hash", models.CharField(max_length=255)),
                ("withdrawal_date", models.DateTimeField(auto_now_add=True)),
                (
                    "gas_fee_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_withdrawal_gas_fee",
                        to="transaction.transaction",
                    ),
                ),
                (
                    "service_fee_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_withdrawal_service_fee",
                        to="transaction.transaction",
                    ),
                ),
                (
                    "withdrawal_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_withdrawal",
                        to="transaction.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "withdrawal_blockchain",
            },
        ),
    ]
