# Generated by Django 4.2.1 on 2023-06-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
        ("withdrawal", "0002_withdrawalblockchain"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                (
                    "bank_country",
                    models.CharField(
                        help_text="Using ISO 3 country code", max_length=3
                    ),
                ),
                ("bank_region", models.CharField(max_length=255)),
                ("bank_branch", models.CharField(max_length=255)),
                ("withdrawal_date", models.DateTimeField(auto_now_add=True)),
                (
                    "service_fee_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_withdrawal_service_fee",
                        to="transaction.transaction",
                    ),
                ),
                (
                    "withdrawal_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_withdrawal",
                        to="transaction.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "withdrawal_bank",
            },
        ),
    ]
