# Generated by Django 5.0.6 on 2024-06-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawal", "0003_withdrawalbank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="withdrawalbank",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="withdrawalblockchain",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="withdrawalsettings",
            options={"ordering": ["id"]},
        ),
    ]
